### ISSUE TITLE
Min and Max date

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-calendar#1]
I took a stab at implementing min and max dates but there must be more to it than what I have here; neither the getters nor the setters are working.

https://github.com/cookieguru/tabris-calendar/commit/a500b2b20287b0771c7b2f15fb21d6df74e5363d

**Comment by mpost** [comment]
@cookieguru Thanks for the contribution. :) You are right that there is something missing. You would need to make the new properties available in https://github.com/cookieguru/tabris-calendar/blob/master/www/calendar.js

**Comment by cookieguru** [comment]
@mpost Awesome, it works now, thanks!  Can you tell me a little bit about the `type` and `cache` properties?  If I'm understanding this correctly the `type` is set to `any` so that either a string, int, or even a float can be passed and java.lang.Long.longValue() will take care of parsing the value.

**Comment by mpost** [comment]
There is documentation on he Properties system here: https://tabrisjs.com/documentation/latest/custom-widgets#properties

**Comment by cookieguru** [comment]
Of course!  I should've checked there first.  Thanks @mpost
